name: first workflow
on: 
  push:

jobs:
  first-job:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
      uses: actions/checkout@v4

      -name: show information
      run: |
        pwd
        ls -la
        whoami
        hostname
        date
        
